### ISSUE TITLE
IE8 not working

### ISSUE THREAD

**Issue by aliceathens** [amsul/pickadate.js#673]
IE8 no longer works. On page load the date and time picker appear broken and will not go away. This is also viewable on your demo page. Can you please advise on a fix for this asap?

Thanks!

![screen shot 2015-04-01 at 12 31 28 pm](https://cloud.githubusercontent.com/assets/9316491/6932852/1a7440d4-d86b-11e4-93e2-9849e320544b.png)

**Comment by ibarral** [comment]
Do you have any news on this? I have the same problem :(

Thanks!

**Comment by ibarral** [comment]
@amsul I think I know how to fix this issue: just add a "display: none;" to the picker root wrapper when it's closed. It's simple, but it works! ;)

**Comment by ginaliao** [comment]
Looks like the CSS property for positioning the picker off the screen was recently changed (in 3.5.5 I believe) to CSS3 transforms which are not supported in IE8.

I fixed this in my <IE8-targeted stylesheet by adding the following:

```css
.picker__holder,
.picker__frame {
	top: 100%;
}

.picker--opened .picker__holder,
.picker--opened .picker__frame {
	top: 0;
}

.picker--opened .picker__frame {
	bottom: 0;
}
```

**Comment by ibarral** [comment]
Thanks!!! it worked perfect! :+1:

**Comment by scheinercc** [comment]
Still the same issue. Why hasn't it been incorporated yet? Or **has IE8 support been dropped** but the Homepage not been updated?

> Supports all modern browsers – and IE8+.

I have applied the display none/block fix now, but even though that works, on the picker the buttons for "today/clear/close" don't work for me. You can only dismiss it hitting "Esc" or choosing a date. This is good enough me atm, but the support should maybe be updated!?

**Comment by DanielRuf** [comment]
MS does not support IE8 anymore.

**Comment by scheinercc** [comment]
I filed #1061 as a follow up bug.
